package entity;
//
// This file was generated by the JPA Modeler
//


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity

public class Client {

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    private double committedLumpSum;

    @Column(unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private double disposableMonthlyAmount;

  
    @ManyToOne(optional = true, targetEntity = RiskLevel.class)
    private RiskLevel clientLevelRiskProfile;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    private double committedMonthlyContributions;

    @Column(unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private String name;

   
    @ManyToOne(optional = true, targetEntity = Country.class)
    private Country country1;

    @Column(unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private double totalLumpSum;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Id @GeneratedValue(strategy=GenerationType.AUTO) 
    private Long id;

    @Column(unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private double netMonthlyIncome;

    @Column(unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private int age;

    public Client() {

    }

    public double getCommittedLumpSum() {
        return this.committedLumpSum;
    }

    public void setCommittedLumpSum(double committedLumpSum) {
        this.committedLumpSum = committedLumpSum;
    }

    public double getDisposableMonthlyAmount() {
        return this.disposableMonthlyAmount;
    }

    public void setDisposableMonthlyAmount(double disposableMonthlyAmount) {
        this.disposableMonthlyAmount = disposableMonthlyAmount;
    }

    public RiskLevel getClientLevelRiskProfile() {
        return this.clientLevelRiskProfile;
    }

    public void setClientLevelRiskProfile(RiskLevel clientLevelRiskProfile) {
        this.clientLevelRiskProfile = clientLevelRiskProfile;
    }

    public double getCommittedMonthlyContributions() {
        return this.committedMonthlyContributions;
    }

    public void setCommittedMonthlyContributions(double committedMonthlyContributions) {
        this.committedMonthlyContributions = committedMonthlyContributions;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Country getCountry1() {
        return this.country1;
    }

    public void setCountry1(Country country1) {
        this.country1 = country1;
    }

    public double getTotalLumpSum() {
        return this.totalLumpSum;
    }

    public void setTotalLumpSum(double totalLumpSum) {
        this.totalLumpSum = totalLumpSum;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getNetMonthlyIncome() {
        return this.netMonthlyIncome;
    }

    public void setNetMonthlyIncome(double netMonthlyIncome) {
        this.netMonthlyIncome = netMonthlyIncome;
    }

    public int getAge() {
        return this.age;
    }

    public void setAge(int age) {
        this.age = age;
    }
}
