package entity;
//
// This file was generated by the JPA Modeler
//

import java.sql.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity

public class InflationRate{

    @Column(unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private Date endDate;

    
    @ManyToOne(optional = true, targetEntity = Country.class)
    private Country country1;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Id @GeneratedValue(strategy=GenerationType.AUTO) 
    private Long id;

    @Column(unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private double annualInflationRatePercent;

    @Column(unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private Date initialDate;

    public InflationRate() {

    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Country getCountry1() {
        return this.country1;
    }

    public void setCountry1(Country country1) {
        this.country1 = country1;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getAnnualInflationRatePercent() {
        return this.annualInflationRatePercent;
    }

    public void setAnnualInflationRatePercent(double annualInflationRatePercent) {
        this.annualInflationRatePercent = annualInflationRatePercent;
    }

    public Date getInitialDate() {
        return this.initialDate;
    }

    public void setInitialDate(Date initialDate) {
        this.initialDate = initialDate;
    }
}
