package entity;
//
// This file was generated by the JPA Modeler
//

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity

public class NominalGrowth {

    @Column(unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private double average;

    
    @ManyToOne(optional = true, targetEntity = RiskLevel.class)
    private RiskLevel riskLevel1;

    @Column(unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private double belowAverage;

    @Column(unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private int term;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Id @GeneratedValue(strategy=GenerationType.AUTO) 
    private Long id;

    @Column(unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private double aboveAverage;

    public NominalGrowth() {

    }

    public double getAverage() {
        return this.average;
    }

    public void setAverage(double average) {
        this.average = average;
    }

    public RiskLevel getRiskLevel1() {
        return this.riskLevel1;
    }

    public void setRiskLevel1(RiskLevel riskLevel1) {
        this.riskLevel1 = riskLevel1;
    }

    public double getBelowAverage() {
        return this.belowAverage;
    }

    public void setBelowAverage(double belowAverage) {
        this.belowAverage = belowAverage;
    }

    public int getTerm() {
        return this.term;
    }

    public void setTerm(int term) {
        this.term = term;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getAboveAverage() {
        return this.aboveAverage;
    }

    public void setAboveAverage(double aboveAverage) {
        this.aboveAverage = aboveAverage;
    }
}
