ALTER TABLE ADVISOR DROP CONSTRAINT FK_ADVISOR_COUNTRY1_ID
ALTER TABLE CLIENT DROP CONSTRAINT FK_CLIENT_COUNTRY1_ID
ALTER TABLE CLIENT DROP CONSTRAINT FK_CLIENT_CLIENTLEVELRISKPROFILE_ID
ALTER TABLE COMPANY DROP CONSTRAINT FK_COMPANY_COUNTRY1_ID
ALTER TABLE GOAL DROP CONSTRAINT FK_GOAL_GOALLEVELRISKPROFILE_ID
ALTER TABLE GOAL DROP CONSTRAINT FK_GOAL_CLIENT1_ID
ALTER TABLE INFLATIONRATE DROP CONSTRAINT FK_INFLATIONRATE_COUNTRY1_ID
ALTER TABLE NOMINALGROWTH DROP CONSTRAINT FK_NOMINALGROWTH_RISKLEVEL1_ID
DROP TABLE ADVISOR CASCADE
DROP TABLE CLIENT CASCADE
DROP TABLE COMPANY CASCADE
DROP TABLE COUNTRY CASCADE
DROP TABLE GOAL CASCADE
DROP TABLE INFLATIONRATE CASCADE
DROP TABLE NOMINALGROWTH CASCADE
DROP TABLE RISKLEVEL CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
